### PR TITLE
Add bounding box params

### PR DESCRIPTION
**Pull request by maciekgroch**
I found it really inconvenient that modification parameters have to be loaded from a *.prm file. I propose a way to create a bounding box for a given shape. As a result, building a box with right dimensions (so that it bounds the modified object whole) is easy and straightforward. 

I ask you to reveiw the code I developed. Should you have any quesitons, contact me.

### CODE REVIEW

**Comment by maciekgroch** [comment]
I think I changed tabs into spaces. That's the reason why the files seem completely different.

**Comment by fsalmoir** [comment]
Hi Maciek, thanks for your pull request.

Unfortunately, I did not get exactly what are your modifications, mainly because, as you wrote, you changed tabs into spaces. Could you restore the tabs please? In this way, the modified files can be uniformly formatted with the whole library.

Thank you so much,

Filippo

**Comment by maciekgroch** [comment]
I uploaded it with tabs. Still the differences can be observed as PyCharm cleaned the code for me. (If the small changes are a problem I can fix that).

What should be reviewed are the methods starting with `build_bounding_box` till the end of the file and correspodning tests.

**Comment by mtezzele** [comment]
I think you converted too many spaces in tabs in params.py. Since it writes and reads specific strings in the files not all the spaces are tabs. Please checkout the code presented before your PR. Moreover please perform a fetch and rebase in order to get the last merge. 
I am sorry for the long waiting but last week was quite a week for me...
Later I will review the code. Thanks!

**Pull request closed without merging**
